name: Build Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install ruby environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Process deploy configuration
        run: |
          sh deploy.sh
          bundle
      - name: Commit build to deploy branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b deploy
          git add .
          git commit -m "Build page" -m "`date`"
          git push -f origin deploy
